name: Flask API CI

on:
  push:
    branches:
      - main

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run Container
        run: docker run -d -p 5000:5000 flask-app

      - name: Wait for API (retry)
        run: |
          for i in {1..10}; do
            curl http://localhost:5000 && break
            sleep 2
          done

      - name: Show running containers
        run: docker ps -a

      - name: Show container logs
        run: docker logs $(docker ps -aq)

   
      - name: Test API
        run: curl http://127.0.0.1:5000